### ISSUE TITLE
Does not remove Blizzard Standard Mythic PlusTimer

### ISSUE THREAD

**Issue by joecobrah** [FabysGames/mythicplustimer#28]
On fresh install, removes the stock timer. After log off and log back in, step into a m+ and it does not replace the timer or quest log like normal.

**Comment by p4nchez** [comment]
can confirm same for me
it dont remove blizz keystone shit ui :D

**Comment by gtonioli** [comment]
Same here

**Comment by fabysdev** [comment]
hmm it does not happen for me ... do you have any other tracker modificiation addons installed?

**Comment by joecobrah** [comment]
I do not have any other timer tracker except this one.

**Comment by fabysdev** [comment]
I does not need to be a timer, any addon that messes with the objective tracker frame could be the cause. do you have anything installed that changes something about the quest frame, like kaliels' tracker

**Comment by joecobrah** [comment]
The only thing I run is Elvui and to track anything is mythic plus timer. I
would get LUA errors if there was an addon or something pushing tracking
when it loads in an instance.

**Comment by garrettmusto** [comment]
Pretty sure the issue is an interaction with Elvui

**Comment by joecobrah** [comment]
Would this be a new interaction? Have ran both almost all of shadowlands
with no negative interaction and the addon removing the stock blizz timer.

**Comment by garrettmusto** [comment]
Only started happening to me during pre-patch/Dragonflight. Was fine all of Shadowlands for me as well.

**Comment by fabysdev** [comment]
hmm, does not happen with active Elvui either for me.
Can you send me your Elvui profile? And maybe any Elvui Plugins you have installed?
thanks

**Comment by gtonioli** [comment]
My profile: https://gist.github.com/gtonioli/0deb9d61b31bc780fffd43a883c36f6b

I'm only using shadow light. But, the issue started before enable it

**Comment by Oysteinz** [comment]
I have the same issue, though it works properly on my main character. The standard blizzard mythic plus timer is for some reason not removed on any of my alts in keys. I also use Elvui.

**Comment by p4nchez** [comment]
i use elvui since years with Mythic PlusTimer no problems in legion bfa shadowlands
but now in dragonflight it want remove the stock blizzard timer when key start
on my side i changed nothing only updated my addons on start of dragonflight
had to install a extra other timer addon that will remove blizz timer but now i have two timers but i want only use Mythic PlusTimer
can you please fix it so it worked like the years before?

**Comment by tsumeno** [comment]
just wanted to ping this issue. i really like this addon for its clean presentation of key objectives, but the "not hiding default timer" makes this unusable.
for now i use another addon called warpdeplete which can hide the default objective.

i would appreciate it if someone has the time to check and fix the issue. if i can help with testing things or gather debug information i would be happy to help.

**Comment by joecobrah** [comment]
I would appreciate it as well since this was the better of the mythic plus
timer addons. It is unfortunate that it affects some and not others, and
weirdly enough, just with this expansion and not in Shadowlands. (Even when
running the exact same addons and weak auras). Not quite sure what may of
broke it for some, but if there was a conflicting issue with this addon or
WA with elv, I am pretty sure we would all be getting LUA errors of some
sort.

Thanks

**Comment by fabysdev** [comment]
I pushed a new version, not sure if that fixes it because i could not reproduce it again after i deleted the WTF directory. 
can you maybe try it, thank you a lot

**Comment by tsumeno** [comment]
Hey, I checked it and sadly it didn't resolve the issue for me :/

**Comment by Lilieth** [comment]
Same for me. Still shows both. I use ElvUI as well.

**Comment by fabysdev** [comment]
i am sorry, i am not finding a reproducible way in my WoW installs. i assume it must be compatibility issue with a other addon.
i would need reproducible steps from a clean WoW install i think.

**Comment by revolive** [comment]
I also had the same issue when ElvUI was enabled and did some digging into this.

I am not a Wow addon expert, but it seems that ElvUI overwrites ObjectiveTrackerFrame after MythicPlusTimer is setting quest_frame.
So I moved the initialization of quest_frame to main.hide_default_tracker. With some other minor changes (check for nil, set to nil after main.show_default_tracker) it seems to resolve the issue on my installation.

I can provide you with the code, but not sure how, push fix branch into this repo or create a fork?

**Comment by fabysdev** [comment]
Hi, 
I released a new version with this fix, 5.1.1.

Can somebody please verify that this issue is fixed?
Thanks a lot

Fabys

**Comment by Lilieth** [comment]
Tested. Works as intended!
Thanks [revolive](https://github.com/revolive)

**Comment by AuroraBTH** [comment]
Hi! This issue still occurs for me with:
* ElvUI 13.33
* MythicPlusTimer 5.1.1

I also have:
* Kaliel's Tracker 6.2.0
* ElvUI WindTools 3.32

It still doesn't hide the default objective tracker even when I disable Kaliel's so I don't think that addon is causing the issue. Could any of you verify which versions you were using?

**Comment by Lilieth** [comment]
I'm always using latest greatest version. Right now 13.33 and still working just fine.

**Comment by AuroraBTH** [comment]
I went in and tried to debug this a bit and even when disabling every other addon other than ElvUI, MPT and Kaliel's I still have this issue
![image](https://github.com/FabysGames/mythicplustimer/assets/11875601/87990875-1df3-445b-bcd4-f9a0c9aba049)
